# Generated by Django 5.0.7 on 2024-07-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'показание', 'verbose_name_plural': 'Показания'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'сенсор', 'verbose_name_plural': 'Сенсоры'},
        ),
    ]
