# Generated by Django 5.0.7 on 2024-07-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_options_alter_sensor_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='created_at',
            new_name='created_tm',
        ),
    ]
